apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubed-prd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/kimkimhun/argocd-app-of-app.git
    targetRevision: main
    path: config/kubed/prd
  destination:
    name: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true


